version: '3'

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfileのファイル名を指定
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=django-db
      - DATABASE_USER=django
      - DATABASE_PASSWORD=django
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
