# Generated by Django 5.0.6 on 2024-07-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='department_id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
