# Generated by Django 5.0.6 on 2024-07-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_user_master_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='position',
            field=models.CharField(default='正社員', max_length=255),
        ),
    ]
