# Generated by Django 5.0.6 on 2024-07-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_user_master_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='company',
        ),
    ]
