# Generated by Django 5.0.6 on 2024-07-30 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_user_master_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '休暇タイプ',
                'verbose_name_plural': '休暇タイプ',
            },
        ),
        migrations.RemoveField(
            model_name='time_sheet',
            name='user',
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user_master')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.leavetype')),
            ],
            options={
                'verbose_name': '休暇リクエスト',
                'verbose_name_plural': '休暇リクエスト',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', '出勤'), ('absent', '欠勤'), ('vacation', '休暇'), ('sick', '病欠')], default='present', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user_master')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.leavetype')),
            ],
            options={
                'verbose_name': '勤怠',
                'verbose_name_plural': '勤怠',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceEvent',
        ),
        migrations.DeleteModel(
            name='time_sheet',
        ),
    ]
