# Generated by Django 5.0.6 on 2024-07-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_user_master_position_alter_company_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='department_id',
            field=models.PositiveIntegerField(default='1', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
