# Generated by Django 5.0.6 on 2024-07-30 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_time', models.DurationField(default='00:00:00')),
                ('shift_type', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user_master')),
            ],
            options={
                'verbose_name': 'シフト',
                'verbose_name_plural': 'シフト',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
