# Generated by Django 5.0.6 on 2024-07-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_user_master_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='position',
        ),
    ]
