# Generated by Django 5.0.6 on 2024-08-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COMPANY',
        ),
    ]
