# Generated by Django 5.0.6 on 2024-08-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_delete_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
