# Generated by Django 5.0.6 on 2024-08-06 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'シフト', 'verbose_name_plural': 'シフト'},
        ),
        migrations.AlterField(
            model_name='shift',
            name='break_time',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('user', 'date')},
        ),
    ]
