# Generated by Django 5.0.6 on 2024-08-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_shift_options_alter_shift_break_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_weekend',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='weekday',
            field=models.CharField(default='Unknown', editable=False, max_length=9),
        ),
    ]
