# Generated by Django 5.0.6 on 2024-08-17 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_shift_is_off_day_alter_shift_break_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user_master')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSheet',
        ),
    ]
