# Generated by Django 5.0.6 on 2024-08-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_timestamp_delete_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='employee_number',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
