# Generated by Django 5.0.6 on 2024-08-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_user_master_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='employee_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
