# Generated by Django 5.0.6 on 2024-09-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_shift_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='shift',
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='clock_in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='clock_out_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='position',
            field=models.CharField(choices=[('社員', 'ß社員'), ('リーダー', 'リーダー'), ('マネージャー', 'マネージャー'), ('課長', '課長'), ('部長', '部長'), ('取締役', '取締役'), ('社長', '社長')], default='社員', max_length=10),
        ),
    ]
