# Generated by Django 5.0.6 on 2024-09-02 13:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_remove_timestamp_shift_alter_timestamp_clock_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employee_number',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.shift'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='clock_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
