# Generated by Django 5.0.6 on 2024-09-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_remove_shift_employee_number_timestamp_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='position',
            field=models.CharField(choices=[('社員', '社員'), ('リーダー', 'リーダー'), ('マネージャー', 'マネージャー'), ('課長', '課長'), ('部長', '部長'), ('取締役', '取締役'), ('社長', '社長')], default='社員', max_length=10),
        ),
    ]
