# Generated by Django 5.0.6 on 2024-09-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_user_master_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_paid_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PaidLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remaining_days', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_leave', to='mainApp.user_master')),
            ],
        ),
    ]
