# Generated by Django 5.0.6 on 2024-09-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_paid_leave',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Paid', '有給'), ('Sick', '病気'), ('personalMatter', '私事')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paidleave',
            name='remaining_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paidleave',
            name='total_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
