# Generated by Django 5.0.6 on 2024-09-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_remove_leaverequest_is_paid_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_paid_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Paid', '有給'), ('Sick', '病気'), ('PersonalMatter', '私事')], max_length=50),
        ),
    ]
