# Generated by Django 5.0.6 on 2024-09-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_leaverequest_is_paid_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='mainApp.user_master'),
        ),
    ]
