# Generated by Django 5.0.6 on 2024-09-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_leaverequest_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='approver',
        ),
    ]
