# Generated by Django 5.0.6 on 2024-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_remove_leaverequest_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_requests', to='mainApp.user_master'),
        ),
    ]
