# Generated by Django 5.0.6 on 2024-09-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_remove_leaverequest_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='applicant_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
