# Generated by Django 5.0.6 on 2024-09-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_leaverequest_applicant_comment_and_more'),
        ('mainApp', '0024_leaverequest_approved_by'),
    ]

    operations = [
    ]
