# Generated by Django 5.1.2 on 2024-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_merge_20240914_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
