# Generated by Django 5.1.2 on 2024-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_alter_user_master_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
