# Generated by Django 5.1.2 on 2024-12-11 13:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_alter_user_master_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['date'], 'verbose_name': 'シフト', 'verbose_name_plural': 'シフト'},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='break_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='mainApp.user_master'),
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_off_day',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='weekday',
        ),
    ]
